export const FETCH_ALL_POSTS_START = "FETCH_ALL_POSTS_START";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_ALL_POST_FAIL = "FETCH_ALL_POST_FAIL";

export const FETCH_POSTS_BY_CATEGORY_START = "FETCH_POSTS_BY_CATEGORY";
export const FETCH_POSTS_BY_CATEGORY_SUCCESS =
    "FETCH_POSTS_BY_CATEGORY_SUCCESS";
export const FETCH_POSTS_BY_CATEGORY_FAIL = "FETCH_POSTS_BY_CATEGORY_FAIL";

